### ISSUE TITLE
[Perf] unneeded files are being included in the final bundle

### ISSUE THREAD

**Issue by sfabriece** [angulartics/angulartics2#130]
* **I'm submitting a ...**
[x ] feature request

* **What is the current behavior?**

When running a bundle analyzer I found that files for all analytics providers were being included. Event though I was only using one.
ie: appinsight, mixpanel, Ga, kissmetrics, etc

* **What is the expected behavior?**

I would like the final bundle to only include the files I'm using. So if i'm just adding support for GA, then all the other providers won't end up in the final bundle.

nb: I've seen other libraries solve this by providing the different providers as separate modules.

* **What is the motivation / use case for changing the behavior?**

To reduce the final size of my webapp.

* **Please tell us about your environment:**

- Angular version: 4.1.3
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I added this in the app.module file.

`Angulartics2Module.forRoot([Angulartics2Mixpanel]),`

**Comment by JonnyBGod** [comment]
Tree shaking should solve this but you can also solve it by importing from the provider specific file instead of providers/index

**Comment by sfabriece** [comment]
I don't import index my import looks like: 

`import { Angulartics2Module, Angulartics2Mixpanel } from 'angulartics2';

my app.module looks like so:

````ts

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    Angulartics2Module.forRoot([Angulartics2Mixpanel])
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I'm building the app with `ng build --aot --prod --stats-json` so any treeshaking built into angular cli is being applied.

**Comment by intellix** [comment]
Aye, the problem is that `angulartics2` exports all of the providers causing 45kb of code just by doing this:

```
import { Angulartics2Module } from 'angulartics2';
```
 
![screenshot 2017-08-04 00 47 35](https://user-images.githubusercontent.com/1162531/28947184-d4abb7b2-78ae-11e7-98cb-49994fb14387.png)

If you remove this line: https://github.com/angulartics/angulartics2/blob/master/src/index.ts#L15 then it drops to 9kb

**Comment by sfabriece** [comment]
@intellix could you create a PR with your fix? 😃

**Comment by intellix** [comment]
Would love to provide a PR but am not sure how to reference the provider files without exporting them. It seems to work when I use something like https://github.com/filipesilva/angular-quickstart-lib/ but I can't quite put my finger on why it doesn't work here. If anyone can figure it out, I'd love to know what causes TS to not be able to resolve those files

**Comment by scttcper** [comment]
Hey, played around with different builds and it looks like unused classes remaining in webpack bundles is a known issue. It was just bumped to webpack 4 roadmap which will be a ways away since 3 is still the next version. https://github.com/webpack/webpack/issues/2899

I think the best idea would be to make individual bundles for each provider and import `angulartics2/providername`. Working on a PR.

**Comment by scttcper** [comment]
I've put just the build on github https://github.com/scttcper/angulartics2-build

```bash
npm i scttcper/angulartics2-build
```

**Comment by scttcper** [comment]
deployed on `npm install angulartics2@next`
