### ISSUE TITLE
Update to Angular2 rc.1

### ISSUE THREAD

**Issue by JulioC** [angulartics/angulartics2#26]
Any plans on updating to rc.1?

I'm still using router-deprecated because the new router is too unstable, so it would be nice if angulartics2 support both for now.

As far as I peeked in the sources, updating wouldn't be too much trouble.

**Comment by MJLang** [comment]
👍

**Comment by JonnyBGod** [comment]
Yes I did a first run at this and trying to follow "location" changes instead of "router" this would allow to easily support any router. But I am having problems with some tests and am a bit out of time.

Will star a PR in a few hours with what I did so far. Will welcome any help with it.

**Comment by NathanWalker** [comment]
I'll take a look @JonnyBGod

**Comment by NathanWalker** [comment]
If you have a branch, please push and I can take from there.

**Comment by JonnyBGod** [comment]
tsk @NathanWalker I just push all my changes to branch rc. might be a bit messy, I was in the middle of it when I had to stop.

**Comment by NathanWalker** [comment]
no worries, I'll see what I can do.

**Comment by JonnyBGod** [comment]
Oh, I just realised that I also have a problem with "DomAdapter". The new one is not working for some reason.

**Comment by JulioC** [comment]
I believe it's due https://github.com/angular/angular/issues/8509

**Comment by NathanWalker** [comment]
@JonnyBGod I've pushed some progress to the branch, it's still not creating the `Router` correctly in the tests but it's following this setup closely now: https://github.com/angular/angular/blob/107016ec124490969484327f0016158190be94a3/modules/%40angular/router/test/integration_spec.ts  so should be able to figure out soon.
I'm going to disable angulartics2 on advanced seed so I can get everything else upgraded and will get it working again once we can finish out the update here.

It would be much simpler if we could get rid of usage of `Router` everywhere in this lib and just:
```
location.subscribe...
```
to router/location changes, however in testing it looks like the `EventEmitter` in `Location` does not emit... may be due to spylocation, not sure but everything appears to suggest relying only on router to change location so not sure what's best atm.

**Comment by JonnyBGod** [comment]
Yes the goal is for the library not to use any router directly.

We can get rid of all router based test as substitute for direct location manipulation tests. If a router does not trigger it is due to an upstream bug on the routers and we should not test for it. We should assume upstream is tested.

So yes, I am up for removing router all together.

**Comment by NathanWalker** [comment]
@JonnyBGod I have something in works that I think will work with no Router in core... but using Router and SpyLocation to test.

**Comment by briananderson1222** [comment]
https://github.com/angulartics/angulartics2/pull/28 👍 I was just looking for this :)
