### ISSUE TITLE
Numeric regex filtering out 404 pageviews

### ISSUE THREAD

**Issue by MaklaCof** [angulartics/angulartics2#265]
**I'm submitting a ...**
* [ ] bug report  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Path that contains only numeric is not send to server (instead home page is send):
```
{ path: "404", component: Containers.NotFoundComponent},   
//Not working: Running command: ga("send", "pageview", "/")

{ path: "404NotFound", component: Containers.NotFoundComponent},   
//Working: Running command: ga("send", "pageview", "/404NotFound")
```
* **What is the expected behavior?**
Expected behaviour is that 404 pageview is send to server:
```
//Not
command: ga("send", "pageview", "/") 
//but
Running command: ga("send", "pageview", "/404")
```

* **What is the motivation / use case for changing the behavior?**
I think it is a bug. Wrong pageview is send to Google.

* **Environment:**
Google Chrome: `Version 66.0.3359.139 (Official Build) (64-bit)`
I tried with version `"angulartics2": "^6.0.0",` and `"angulartics2": "^5.3.0",`

please run the following and copy the output
```sh

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.3
Node: 9.4.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack-bundle-analyzer: 2.11.1
webpack-hot-middleware: 2.21.2
webpack-merge: 4.1.2
webpack: 3.11.0
```

**Comment by fhewitt** [comment]
@MaklaCof

**Thinking**
It's not a bug: clearIds remove numbers from the path and that's the expected behaviour.

Now I imagine that preserving numeric Id on path of length 1 could be a good idea. I can't see how this could be wrong. But it looks like a breaking change. @scttcper what do you think?

An interesting feature could be the ability to pass a 'pageTrack' data to routing that would override settings for a given route event. But this is a relatively large change, for a relatively small use case.

**Good practice**
I would suggest to avoid page redirection on 404. In some case, it's strongly better for the user to be able to reedit the URL (i.e. if he copy a long link from a printed poster on his phone, and he make a mistake on a single char).

**Workaround**
The configuration idsRegExp can maybe solve your issue: 

`^(?!404)[0-9]*$` will match your need by removing any numeric ids, outside of 404. But it also mean that if you have `article/404/edit`, this will also be ignored from the clearId process, which is eventually problematic.

If you have only Guid IDs, you can ignore the number and use: `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`

**Comment by scttcper** [comment]
i'd just push another event or pageview on 404 that gets you the data you need.
