### ISSUE TITLE
Support for piwik

### ISSUE THREAD

**Issue by djdillon** [angulartics/angulartics2#31]
It looks like there is no longer support for piwik. Is this in the works or is it no longer to be supported?

**Comment by JonnyBGod** [comment]
We decided to implement the most used providers for now and will be implementing new ones as needed/requested.

Because angular2 is changing a lot we are not planning for new providers until official release.

We do however gladly accept PRs. It is fairly easy to create a new provider. If your up for it we can help you. You can also create a separate repo for your provider if you prefer.

**Comment by briananderson1222** [comment]
https://github.com/angulartics/angulartics2/pull/37

**Comment by djdillon** [comment]
Thanks Brian for letting me know about this and thanks to @kwv for submitting the change.
