### ISSUE TITLE
Tracking events don't display

### ISSUE THREAD

**Issue by lkhgvsuren** [angulartics/angulartics2#331]
**For support questions, please consider using [Gitter - Chat](https://gitter.im/angulartics/angulartics2)**

**I'm submitting a ...**

[ ] bug report  

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Only real-time page-view data displays. But total page-view, site speed and events are not displayed.

* **Environment:**

Angular CLI: 7.0.7
Node: 10.14.2
OS: darwin x64
Angular: 7.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cdk                      7.2.0
@angular/cli                      7.0.7
@angular/fire                     5.1.1
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.2.0
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

**Comment by fhewitt** [comment]
Angulartic offer 20 different provider. It's important to specify which one you use.

Based on the assumption that it's Google Analytics, the important point is to know that the stats are normally no not real time. (outside of the real time section). You should wait some hours (no more than a day) before seeing the results.

Otherwise, I would suggest to check if you use a filtered view. Maybe your data from local/dev environment are ignored.
