### ISSUE TITLE
Page views not being tracked with router 3.0.0-alpha.8

### ISSUE THREAD

**Issue by michaelbailey** [angulartics/angulartics2#48]
I am using @angular/router 3.0.0-alpha.8 and no page views are being tracked. All of my events are fired correctly, but no page loads are sent to Google Analytics. This includes the initial page load.

**Comment by stefda** [comment]
I suspect this is because the page views tracking (as implemented at the moment) is based on the `Location` class while with the new router, one should use the `Router.events` Observable instead.

If you're adventurous, take a look at the contructor in `scr/core/angulartics2.ts` and consider replacing `location: Location` with `router: Router` and changing the constructor code to something like:

```
router.events.subscribe(event => {
    if (event is NavigationStart) {
        this.trackLocation(...);
    }
}
```

Haven't tried this myself but have a feeling that it should lead you in the right direction.

**Comment by JonnyBGod** [comment]
This is the case yes. We were trying to keep this library agnostic to the different routers. You can follow discussion at https://github.com/angulartics/angulartics2/issues/29.

Because there is still not a final decision that we know to this matter, I mean if navigation subscribe should be triggered when the router is changed. We are not changing back to listen to router changes. So please be patient, we are almost there and once Angular2 is officially release we will take action as soon as possible.

Meanwhile there are some workaround you can follow on https://github.com/angulartics/angulartics2/issues/29.

**Comment by JonnyBGod** [comment]
duplicate https://www.facebook.com/etjusticepourtous/videos/10155026335137519/
