### ISSUE TITLE
Don't use private Angular imports

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angulartics/angulartics2#54]
In https://github.com/angulartics/angulartics2/blob/ef410c1a12120783abdafca28ab3b71a844f1d0b/src/core/angulartics2On.ts#L3 you've got `import {getDOM} from '@angular/platform-browser/src/dom/dom_adapter'` which is private import. From RC6 release of Angular it will pretty much impossible to use private imports which means that people won't be able to use this library with RC6. It is currently blocking https://github.com/ng-bootstrap/ng-bootstrap migration.

From what I can see this import is just used for some non-essential utils and could be probably removed.

**Comment by JonnyBGod** [comment]
This will have to be rewritten for sure. Atm it is used to try to infer the type of action to be dispatched mainly for easier usage.

I will not focus on it for now. But a PR is welcome as long as it retains functionality. Once Angular2 is stable or access to getDOM is blocked I will review this.

**Comment by pkozlowski-opensource** [comment]
> Once Angular2 is stable or access to getDOM is blocked I will review this.

It will be the case as soon as rc6 is out - eta 2 days. 

> I will not focus on it for now.

OK. But the net effect is that this lib won't be usable with rc6.

**Comment by JonnyBGod** [comment]
I don't see getDOM export removed from current master or find any references in upcoming PRs.

It seems to me that getDOM will still be available on RC6 at least for now.

I don't really like this solution because it potentially breaks compatibility with other environments such as server, web worker or nativescript. But I prefer to have some time to look into a better solution while trying to keep functionality.

That said if this really breaks rc6 compatibility once it is released I will comment out as soon as possible and release without this feature.

**Comment by pkozlowski-opensource** [comment]
> I don't see getDOM export removed from current master or find any references in upcoming PRs. It seems to me that getDOM will still be available on RC6 at least for now.

It is not removed but now ng2 packages are just publishing ES6 files only so with your private imports people would have to setup ES6 -> ES5 transpilation. 

> That said if this really breaks rc6 compatibility once it is released I will comment out as soon as possible and release without this feature.

It does. Or forces people to setup ES6 -> ES5 transpilation pipeline. Not to mention that this is a private API and can be changed / removed at any point.

**Comment by JonnyBGod** [comment]
You were totally right about this.

I have commented out the code related to this and skipped the test for now.

This feature will probably be completely removed in the future as I suspect that there is now way to implement it to work with every platform. Need to study it a bit more before removing completely though.

If that turns out to be the case, I will try to bring it back as a plugin.
